apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-deployment
  labels:
    app: react-todo
spec:
  replicas: 2 # Kubernetes will run 2 identical copies of your app for redundancy
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
      - name: react-todo-container
        image: zyzmann/react-todo-app:47a32a721fe171424f2133b8d6714ebb4d9dc00d # Updated automatically by GitHub Actions
        imagePullPolicy: Always
        ports:
        - containerPort: 80

